package org.idp.wallet.verifiable_credentials_library.domain.type.oidc

data class ClientConfigurationRequest(
    val redirectUris: List<String> = ArrayList(),
    val tokenEndpointAuthMethod: String = "",
    val grantTypes: List<String> = ArrayList(),
    val responseTypes: List<String> = ArrayList(),
    val clientName: String = "",
    val clientUri: String = "",
    val logoUri: String = "",
    val scope: String = "",
    val contacts: String = "",
    val tosUri: String = "",
    val policyUri: String = "",
    val jwksUri: String? = null,
    val jwks: String? = null,
    val softwareId: String = "",
    val softwareVersion: String = "",
    val requestUris: List<String> = ArrayList(),
    val backchannelTokenDeliveryMode: String = "",
    val backchannelClientNotificationEndpoint: String = "",
    val backchannelAuthenticationRequestSigningAlg: String = "",
    val backchannelUserCodeParameter: Boolean? = null,
    val applicationType: String = "native",
    val idTokenEncryptedResponseAlg: String? = null,
    val idTokenEncryptedResponseEnc: String? = null,
    val authorizationDetailsTypes: List<String> = ArrayList(),
    val tlsClientAuthSubjectDn: String? = null,
    val tlsClientAuthSanDns: String? = null,
    val tlsClientAuthSanUri: String? = null,
    val tlsClientAuthSanIp: String? = null,
    val tlsClientAuthSanEmail: String? = null,
    val tlsClientCertificateBoundAccessTokens: Boolean = false,
    val authorizationSignedResponseAlg: String? = null,
    val authorizationEncryptedResponseAlg: String? = null,
    val authorizationEncryptedResponseEnc: String? = null,
)
